version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: togo-tickets-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: togotickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

#   adminer:
#     image: adminer
#     container_name: togo-tickets-adminer
#     restart: always
#     ports:
#       - "8080:8080"

volumes:
  postgres_data:
